# Generated by Django 5.1.3 on 2024-11-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_stock_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.ForeignKey(blank=True, limit_choices_to={'isFinal': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.component'),
        ),
    ]
