# Generated by Django 5.1.3 on 2024-11-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_component_isfinal_component_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.CreateModel(
            name='SupplierComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(default='pcs', max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.component')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='suppliercComponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.suppliercomponent'),
        ),
    ]
