# Generated by Django 5.1.3 on 2024-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_component_supplier_remove_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
