# Generated by Django 5.1.3 on 2024-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_supplierccomponent_stock_suppliercomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='units',
            field=models.CharField(default='pcs', max_length=100),
        ),
    ]
