# Generated by Django 5.1.3 on 2024-11-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_stock_quantity_stock_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='serialNumber',
        ),
        migrations.CreateModel(
            name='ProductSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.product')),
            ],
        ),
    ]
