# Generated by Django 5.1.3 on 2024-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_stock_serialnumber_productserialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='units',
            field=models.CharField(default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.CharField(default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='units',
            field=models.CharField(default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='units',
            field=models.CharField(default='pcs', max_length=5),
        ),
    ]
