# Generated by Django 5.1.3 on 2024-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_component_units_alter_stock_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='batchNumber',
            field=models.CharField(default='!! UNSET !!', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
