# Generated by Django 5.1.3 on 2024-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_stock_attributes_delete_stockattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='components',
            field=models.ManyToManyField(through='web.SupplierComponent', to='web.component'),
        ),
    ]
