# Generated by Django 5.1.3 on 2024-11-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_supplier_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(default='pcs', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.component')),
            ],
        ),
    ]
