# Generated by Django 5.1.3 on 2024-11-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_buildorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildorder',
            name='dateCompleted',
        ),
        migrations.RemoveField(
            model_name='buildorder',
            name='dateIssued',
        ),
    ]
