# Generated by Django 5.1.3 on 2024-11-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_buildorder_datecompleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(default='pcs', max_length=5)),
                ('batchNumber', models.CharField(editable=False, max_length=100)),
                ('buildOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.buildorder')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.component')),
            ],
        ),
    ]
