# Generated by Django 5.1.3 on 2024-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_buildorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildorder',
            name='component',
        ),
        migrations.AddField(
            model_name='buildorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
