# Generated by Django 5.1.3 on 2024-11-24 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_buildorder_component_buildorder_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='buildorder',
            name='units',
        ),
        migrations.AddField(
            model_name='buildorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
