# Generated by Django 5.1.3 on 2024-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_buildorder_quantity_remove_buildorder_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserialnumber',
            name='isAssigned',
            field=models.BooleanField(default=False),
        ),
    ]
